### ISSUE TITLE
ce-popover-item__icon button submits the parent form

### ISSUE THREAD

**Issue by atstockland** [sebmeister2077/editorjs-indent-tune#1]
Clicking the indent button causes the parent form to submit.  Is it possible to not use a button element for the indent functionality?  Or, add 'type="button"' to it?

I believe adding 'type="button"' to the button element will prevent it from submitting the form.

```
<button type="button" class="ce-popover-item__icon" data-tune-indent-right="" style="margin-left:10px;">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
<path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M9.58284 17.5L14.4414 12.6414C14.5195 12.5633 14.5195 12.4367 14.4414 12.3586L9.58284 7.5"></path>
</svg>
</button>
```

**Comment by CodyPChristian** [comment]
Yep, I hit this same problem as well.

**Comment by CodyPChristian** [comment]
@atstockland I have fixed the issue in my PR #2

**Comment by atstockland** [comment]
> @atstockland I have fixed the issue in my PR #2 

Awesome!  Thank you!

**Comment by CodyPChristian** [comment]
> > @atstockland I have fixed the issue in my PR #2
> 
> Awesome! Thank you!

No Problem, hopefully @sebmeister2077 doesnt mine merging it in. In the meantime you can use my release if its urgent as I did build / tag it in my fork for now since I needed it asap.

**Comment by sebmeister2077** [comment]
Hello, thank you for mentioning me, yes i will merge this later today 😄

**Comment by sebmeister2077** [comment]
@atstockland I've published a new version on npm tixing this issue

**Comment by atstockland** [comment]
> @atstockland I've published a new version on npm tixing this issue

Fantastic!  Thank you so much!!!
