### ISSUE TITLE
Idea: Show indent level visually in editor

### ISSUE THREAD

**Issue by CodyPChristian** [sebmeister2077/editorjs-indent-tune#3]
Hey @sebmeister2077 I had an idea and thats why I added the class mentioned in my PR #2 however I wasnt sure of the best way to go about it. 

Showing a visual indicator in the UI for the ident. I assume doing a calculation from the far left side to the start of the div that wraps the content? See image below in yellow. A lot of nesting going on there so wasnt sure of the best way.

Thoughts?

![rte](https://github.com/sebmeister2077/editorjs-indent-tune/assets/165797/75bd6dbd-89f4-48d1-81fd-e64c13dd2905)

**Comment by sebmeister2077** [comment]
I like the idea. Would be cool if we also have support for the amount of indent there is on a block for styling, and we need to take into consideration if the user has also an alignment tune in his editor. 😄 

I'd suggest we/you create a separate PR for this feature. I will work on it around 6-7 hours from now after work if you didnt have time till then

**Comment by sebmeister2077** [comment]
I've done some investigating, and we dont need to calculate anything since we already know how much indent is applied (in pixels), only thing i dont know yet is if i should use a separate html element or if i should use `.ce-block__content::before` .


Update will need to use the element rects and calculate widths

**Comment by CodyPChristian** [comment]
@sebmeister2077 thanks for digging into that and so far looks good to me

**Comment by CodyPChristian** [comment]
@sebmeister2077  Used latest version in production and everything worked great! Thanks!
